### ISSUE TITLE
Verbs' infinitives are a mess

### ISSUE THREAD

**Issue by iummy17** [JimmyPaolini/Lexico#39]
Verbs' infinitives aren't sorted correctly. For example Act.Perf is actually Pas.Pres. and Act.Fut is Act.Perf, while Pas.Pres is Pas.Perf,Pas.Perf is Act.Fut.; Take a look on the picture to understand what I mean.
![bug](https://user-images.githubusercontent.com/84772088/119471606-bb71ed00-bd49-11eb-9893-615f317c84c7.png)

**Comment by JimmyPaolini** [comment]
Yikes thanks for catching this! Fixing it ASAP and long term I'd like to write automated tests to catch bugs like this.
